GoogleAuthentication/Controllers/ChatController.cs
using GoogleAuthentication.Models.UserMaster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoogleAuthentication.Controllers
{
    [Authorize]
    public class ChatController : Controller
    {
        private readonly IUserMaster _user;

        public ChatController(IUserMaster user)
        {
            _user = user;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ShowOnlineUser()
        {
            return View();
        }
        [HttpGet]
        public  IActionResult GetALLUser()
        {
            string userid = HttpContext.Session.GetString("UserName");
            var res =  _user.GetAllUser(userid);
            return Content(res);
        }
        [HttpGet]
        public IActionResult GetALLChat(string selectUser)
        {
            string userid = HttpContext.Session.GetString("UserName");    
            var res =  _user.GellAllChat(userid, selectUser);
            return Content(res);
        }
    }
}

GoogleAuthentication/Controllers/PaymentController.cs
using GoogleAuthentication.Models.Payment;
using Microsoft.AspNetCore.Mvc;
using Razorpay.Api;
using System.Security.Cryptography;
using System.Text;

namespace GoogleAuthentication.Controllers
{
    public class PaymentController : Controller
    {
        private readonly string _key = "rzp_test_6Vb4Z0apv502SS";
        private readonly string _secret = "d3DCDX5gwavbEoYABlltSglz";
        public IActionResult Index()
        {
            //FetchAllPayment();
             var model = new PaymentModel() { Amount = 1, Name = "Vinay Singh", Mobile = "8957884575", Email = "vinaysingh.ct@gmail.com" };
            return View(model);
        }
        [HttpPost]
        public IActionResult SubmitPayment(PaymentModel obj)
        {

            OrderModel order = new OrderModel()
            {
                OrderAmount = obj.Amount,
                Currency = "INR",
                Payment_Capture = 0,
                Notes = new Dictionary<string, string>()
                {
                    {"note 1"," first note while creating Order" }
                }
            };
            var orderId = createOrder(order);
            RazorPayOptionsModel razorPayOptions = new RazorPayOptionsModel()
            {
                Key = _key,
                AmountInSubUnits = order.OrderAmountInSubUnits,
                Currency = order.Currency,
                Name = "VinaySingh",
                Description = "Test",
                ImagelogUr1 = "",
                OrderId = orderId,
                ProfileName = obj.Name,
                ProfileContact = obj.Mobile,
                ProfileEmail = obj.Email,
                Notes = new Dictionary<string, string>()
                {
                    {"note 1","This is test paymet Note" }
                }

            };
            return View(razorPayOptions);
        }
        private string createOrder(OrderModel order)
        {
            try
            {
                RazorpayClient client = new RazorpayClient(_key, _secret);
                Dictionary<string, object> options = new Dictionary<string, object>();
                options.Add("amount", order.OrderAmountInSubUnits);
                options.Add("currency", order.Currency);
                options.Add("payment_capture", order.Payment_Capture);
                options.Add("notes", order.Notes);

                // create a order

                Order orderResponse = client.Order.Create(options);
                var orderId = orderResponse.Attributes["id"].ToString();
                return orderId;
            }
            catch (Exception ex)
            {

                return null;
            }
        }
        public ViewResult AfterPayment()
        {

            var paymentStatus = Request.Form["paymentstatus"].ToString();
            if (paymentStatus=="Fail")
            {
                return View("Fail");
            }
            var orderId = Request.Form["orderid"].ToString();
            var paymentId = Request.Form["paymentid"].ToString();
            var signature = Request.Form["signature"].ToString();
            var validSignature = CompareSignature(orderId, paymentId, signature);
            if (validSignature)
            {
                ViewBag.Message = "Congratilation!! Payment was successful.";
                return View("Success");
            }
            else
            {
                return View("Fail");
            }
                
        }
        private bool CompareSignature(string orderId, string paymentId, string razorPaySignature)
        {
            var text = orderId + "|" + paymentId;
            var secret = _secret;
            var genratedSignature = CalculateSHA256(text, secret);

            if (genratedSignature == razorPaySignature)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        private string CalculateSHA256(string text, string secret)
        {
            string result = "";
            var enc = Encoding.Default;
            byte[]
            baText2BeHashed = enc.GetBytes(text),
              baSalt = enc.GetBytes(secret);
            System.Security.Cryptography.HMACSHA256 hasher = new HMACSHA256(baSalt);
            byte[] baHashedText = hasher.ComputeHash(baText2BeHashed);
            result = string.Join("", baHashedText.ToList().Select(b => b.ToString("x2")).ToArray());
            return result;
        }
        public ViewResult Capture()
        {
            return View();
        }
        public ViewResult CapturePayment(string paymentId)
        {
            try
            {
                RazorpayClient client = new RazorpayClient(_key, _secret);
                Razorpay.Api.Payment payment = client.Payment.Fetch(paymentId);
                var amount = payment.Attributes["amount"];
                var currency = payment.Attributes["currency"];
                Dictionary<string, object> options = new Dictionary<string, object>();
                options.Add("amount", amount);
                options.Add("currency", currency);
                Razorpay.Api.Payment paymentCaptured = payment.Capture(options);
                ViewBag.Message = "Payment captured!";
                return View("Success");
            }
            catch (Exception ex)
            {

                return View("Fail");
            }

        }
        public IActionResult FetchAllPayment()
        {
            RazorpayClient client = new RazorpayClient(_key, _secret);
           List<Razorpay.Api.Payment> payment = client.Payment.All();
            var res = Json(new { payment });
            return (res) ;
        }

    }
}

GoogleAuthentication/Controllers/TestController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GoogleAuthentication.Controllers
{
    public class TestController : Controller
    {
        private readonly IWebHostEnvironment hostEnvironment;

        public TestController(IWebHostEnvironment hostEnvironment )
        {
            this.hostEnvironment = hostEnvironment;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            var  test = new Test(this.hostEnvironment);
           var resp= test.Main();
            var res = File(resp, "application/octet-stream", "era.jpg");
            return res;
            //return View();
        }
    }
}

GoogleAuthentication/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GoogleAuthentication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GoogleAuthentication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GoogleAuthentication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Chat" asp-action="Index">Chat</a>
                        </li> <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Payment" asp-action="Index">Payment</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Index">Test</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="main-login">
                @if (Context.Session.GetString("UserId") == null)
                {
                    <button class="login-button">Login</button>
                    <div class="main-login-content">
                        <a asp-controller="Account" asp-action="GoogleLogin"><img class="logo-img" src="~/images/google.png" /> Google</a>
                        <a asp-controller="Account" asp-action="FacebookLogin"><img class="logo-img" src="~/images/facebook.png" /> Faceboook</a>
                    </div>
                }
                else
                {
                    <div class="main-login">
                        <a asp-controller="Account" asp-action="Logout">
                            <button class="logout-button">Logout</button>
                        </a>
                    </div>

                }


            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GoogleAuthentication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>